name: Healer
version: "1.0"
author: socialclubz.com
api: ["1.0.0"]
main: me.socialclubz.com.healer
commands:
  heal:
    description: Recover your hearts
    permission: social.heal
  eat:
    description: Recover your hunger
    permission: social.eat
  healer:
    description: Completly heals all
    permission: social.healer
  ext:
    description: Takes the fire away
    permission: social.ext